source 'https://rubygems.org'

gem 'pry'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-activerecord'
gem 'rake'
gem 'sqlite3'
gem 'facebook-messenger'
gem 'rack'
gem 'sinatra-syslog'
gem 'sinatra-mapping'
